version: "3.8"

services:
  node:
      container_name: remove-meta
      image: "node:latest"
      tty: true
      working_dir: /var/www/app
      volumes:
        - ./:/var/www/app/
      ports:
        - 3000:3000