version: "3.8"

services:
  node:
      container_name: remove-meta
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www/app/
      ports:
        - 3000:3000